import type { Product, Testimonial } from './types';

export const products: Product[] = [
  {
    id: 'thekua-classic-ghee',
    name: 'Classic Ghee Thekua',
    description: 'The authentic taste of Bihar, made with pure ghee and whole wheat.',
    longDescription: 'Our Classic Ghee Thekua is a tribute to the timeless recipe that has been cherished for generations. Made with premium whole wheat flour, sweetened with jaggery, and fried to a perfect golden-brown in pure desi ghee, each bite offers a crunchy texture and a rich, nutty flavor. It\'s the perfect snack for any time of the day.',
    images: [{ id: 'new-thekua-1', alt: 'Classic Ghee Thekua' }, { id: 'thekua-2', alt: 'A stack of Thekua' }],
    price: 250,
    tags: ['classic', 'ghee', 'bestseller'],
    packSizes: ['250g', '500g', '1kg'],
    category: 'classic',
  },
  {
    id: 'thekua-coconut-crunch',
    name: 'Coconut Crunch Thekua',
    description: 'A delightful twist with the tropical flavor of dried coconut.',
    longDescription: 'Experience a tropical escape with our Coconut Crunch Thekua. We\'ve added generous amounts of finely grated dried coconut to our traditional dough, creating a unique texture and a subtly sweet, aromatic flavor profile. It\'s a modern take on a classic that will leave you wanting more.',
    images: [{ id: 'new-thekua-2', alt: 'Coconut Crunch Thekua' }, { id: 'thekua-4', alt: 'Thekua with coconut flakes' }],
    price: 280,
    tags: ['coconut', 'new-flavor', 'bestseller'],
    packSizes: ['250g', '500g'],
    category: 'classic',
  },
  {
    id: 'thekua-dry-fruit-delight',
    name: 'Dry Fruit Delight Thekua',
    description: 'Loaded with premium nuts and raisins for a royal treat.',
    longDescription: 'Indulge in the richness of our Dry Fruit Delight Thekua. This luxurious version is packed with a mix of chopped almonds, cashews, and sweet raisins. The crunch of the nuts and the sweetness of the raisins perfectly complement the rustic flavor of the Thekua, making it a truly decadent snack.',
    images: [{ id: 'thekua-5', alt: 'Dry Fruit Delight Thekua' }, { id: 'thekua-6', alt: 'Thekua with dry fruits' }],
    price: 350,
    tags: ['dry-fruit', 'premium', 'bestseller'],
    packSizes: ['500g', '1kg'],
    category: 'classic',
  },
  {
    id: 'thekua-sugar-free',
    name: 'Sugar-Free Thekua',
    description: 'The same great taste, sweetened naturally with jaggery.',
    longDescription: 'For our health-conscious customers, we offer a Sugar-Free Thekua that doesn\'t compromise on taste. Sweetened entirely with organic jaggery, this version retains the authentic flavor while being a healthier alternative. Enjoy the guilt-free pleasure of this traditional snack.',
    images: [{ id: 'thekua-7', alt: 'Sugar-Free Thekua' }],
    price: 270,
    tags: ['sugar-free', 'healthy', 'bestseller'],
    packSizes: ['250g', '500g'],
    category: 'healthy',
  },
  {
    id: 'combo-festive-pack',
    name: 'Festive Combo Pack',
    description: 'An assortment of our best Thekuas, perfect for gifting.',
    longDescription: 'Our Festive Combo Pack is the perfect way to celebrate any occasion. It includes a curated selection of our Classic Ghee, Coconut Crunch, and Dry Fruit Delight Thekuas. Beautifully packaged, it makes for an ideal gift for loved ones or a wonderful treat for yourself.',
    images: [{ id: 'thekua-8', alt: 'Festive Combo Pack' }],
    price: 800,
    tags: ['combo', 'gifting', 'festive', 'bestseller', 'special-offer'],
    packSizes: ['750g'],
    category: 'gift',
  },
  {
    id: 'chhath-puja-special',
    name: 'Chhath Puja Special Thekua',
    description: 'Authentic Thekua made especially for Chhath Puja rituals.',
    longDescription: 'Celebrate Chhath Puja with our specially prepared Thekua. Made with the purest ingredients and following traditional methods, these are perfect for offering as prasad and sharing with family. Their authentic taste and texture are a tribute to this sacred festival.',
    images: [{ id: 'thekua-1', alt: 'Chhath Puja Thekua' }],
    price: 300,
    tags: ['puja', 'chhath', 'traditional', 'bestseller'],
    packSizes: ['500g', '1kg'],
    category: 'puja',
  },
  {
    id: 'diwali-delight-box',
    name: 'Diwali Delight Box',
    description: 'A beautiful box of assorted Thekuas for the festival of lights.',
    longDescription: 'Light up your Diwali celebrations with our Diwali Delight Box. This special assortment features a mix of our most popular Thekuas, elegantly packaged to be the perfect gift for your friends and family during the festive season.',
    images: [{ id: 'thekua-8', alt: 'Diwali Thekua Box' }],
    price: 850,
    tags: ['diwali', 'festive', 'gifting', 'special-offer'],
    packSizes: ['800g'],
    category: 'puja',
  },
  {
    id: 'sweet-thekua-sampler',
    name: 'Sweet Thekua Sampler',
    description: 'A collection of our sweetest Thekua varieties.',
    longDescription: 'For those with a sweet tooth, our Sweet Thekua Sampler offers a delightful assortment of our most beloved sweet flavors. Perfect for dessert or a sweet snack.',
    images: [{ id: 'thekua-9', alt: 'Sweet Thekua Sampler' }],
    price: 450,
    tags: ['sweet', 'sampler', 'combo', 'bestseller'],
    packSizes: ['500g'],
    category: 'sweet',
  },
  {
    id: 'savory-thekua-bites',
    name: 'Savory Thekua Bites',
    description: 'A spicy and savory twist on the traditional Thekua.',
    longDescription: 'Who says Thekua has to be sweet? Our Savory Thekua Bites are seasoned with a blend of traditional Indian spices for a crunchy, savory snack that pairs perfectly with tea.',
    images: [{ id: 'thekua-10', alt: 'Savory Thekua Bites' }],
    price: 300,
    tags: ['savory', 'spicy'],
    packSizes: ['250g', '500g'],
    category: 'savory',
  },
  {
    id: 'healthy-options-pack',
    name: 'Healthy Options Pack',
    description: 'A combination of Sugar-Free and Whole-Wheat Thekua.',
    longDescription: 'Enjoy our delicious Thekua without the guilt. This pack includes our Sugar-Free and other whole-wheat options for a healthier snacking experience.',
    images: [{ id: 'thekua-11', alt: 'Healthy Thekua Options' }],
    price: 550,
    tags: ['healthy', 'sugar-free', 'combo', 'special-offer'],
    packSizes: ['600g'],
    category: 'healthy',
  },
  {
    id: 'thekua-wedding-favors',
    name: 'Thekua Wedding Favors',
    description: 'Customizable Thekua packs for your special occasions.',
    longDescription: 'Add a traditional touch to your celebrations with our customizable Thekua gift packs. Perfect as wedding favors, corporate gifts, or for any special event.',
    images: [{ id: 'thekua-12', alt: 'Thekua Wedding Favors' }],
    price: 1200,
    tags: ['gifting', 'wedding', 'custom'],
    packSizes: ['1.5kg'],
    category: 'gift',
  },
  {
    id: 'mini-ghee-thekua',
    name: 'Mini Ghee Thekua',
    description: 'Bite-sized versions of our classic ghee thekua.',
    longDescription: 'Enjoy the same authentic taste of our Classic Ghee Thekua in a smaller, bite-sized form. Perfect for snacking on the go or for serving at parties.',
    images: [{ id: 'new-thekua-2', alt: 'Mini Ghee Thekua' }],
    price: 260,
    tags: ['classic', 'ghee', 'mini', 'bestseller'],
    packSizes: ['250g', '500g'],
    category: 'classic',
  },
  {
    id: 'puja-prasad-thekua',
    name: 'Puja Prasad Thekua',
    description: 'Pure and simple thekua for your daily puja rituals.',
    longDescription: 'Our Puja Prasad Thekua is made with simple, pure ingredients suitable for religious offerings. Its authentic preparation makes it a perfect addition to your daily prayers.',
    images: [{ id: 'thekua-13', alt: 'Puja Prasad Thekua' }],
    price: 280,
    tags: ['puja', 'traditional', 'bestseller'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'jaggery-sesame-thekua',
    name: 'Jaggery Sesame Thekua',
    description: 'Thekua enriched with the goodness of sesame seeds.',
    longDescription: 'A wholesome variation, our Jaggery Sesame Thekua is packed with the nutty flavor of roasted sesame seeds, blended with the natural sweetness of jaggery.',
    images: [{ id: 'thekua-14', alt: 'Jaggery Sesame Thekua' }],
    price: 290,
    tags: ['healthy', 'sesame', 'bestseller'],
    packSizes: ['500g'],
    category: 'healthy',
  },
  {
    id: 'navratri-special-thekua',
    name: 'Navratri Special Thekua',
    description: 'Fasting-friendly Thekua for Navratri celebrations.',
    longDescription: 'Specially made for Navratri fasting, this Thekua uses ingredients that are suitable for vrat. Celebrate the festival with this traditional and delicious snack.',
    images: [{ id: 'thekua-15', alt: 'Navratri Special Thekua' }],
    price: 320,
    tags: ['puja', 'navratri', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'ganesh-chaturthi-modak-thekua',
    name: 'Ganesh Chaturthi Modak Thekua',
    description: 'A creative fusion of Thekua and Modak flavors.',
    longDescription: 'Celebrate Ganesh Chaturthi with a unique twist. Our Modak Thekua infuses the traditional flavors of coconut and jaggery from modak into the crunchy texture of thekua.',
    images: [{ id: 'thekua-16', alt: 'Ganesh Chaturthi Modak Thekua' }],
    price: 350,
    tags: ['puja', 'ganesh-chaturthi', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'karwa-chauth-thekua-set',
    name: 'Karwa Chauth Thekua Set',
    description: 'A special set of Thekua for Karwa Chauth rituals.',
    longDescription: 'Complete your Karwa Chauth rituals with our specially prepared Thekua. Made with love and traditional ingredients, it\'s the perfect offering.',
    images: [{ id: 'thekua-17', alt: 'Karwa Chauth Thekua Set' }],
    price: 310,
    tags: ['puja', 'karwa-chauth', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'bhai-dooj-gift-pack',
    name: 'Bhai Dooj Gift Pack',
    description: 'A sweet gift to celebrate the bond of siblings.',
    longDescription: 'This Bhai Dooj, gift your brother a pack of delicious, assorted Thekua. A sweet way to celebrate your special bond.',
    images: [{ id: 'thekua-18', alt: 'Bhai Dooj Gift Pack' }],
    price: 480,
    tags: ['gifting', 'bhai-dooj', 'festive', 'special-offer'],
    packSizes: ['600g'],
    category: 'puja',
  },
  {
    id: 'makar-sankranti-special',
    name: 'Makar Sankranti Special Thekua',
    description: 'Thekua made with sesame and jaggery for the harvest festival.',
    longDescription: 'Celebrate Makar Sankranti with our special Til-Gur Thekua. Made with sesame seeds and jaggery, it is the perfect traditional snack for the occasion.',
    images: [{ id: 'thekua-19', alt: 'Makar Sankranti Special' }],
    price: 330,
    tags: ['puja', 'makar-sankranti', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'holi-gulaal-thekua',
    name: 'Holi Gulaal Thekua',
    description: 'Colorful and festive Thekua for your Holi celebrations.',
    longDescription: 'Add more color to your Holi celebrations with our Gulaal Thekua. A festive and fun take on the traditional snack.',
    images: [{ id: 'thekua-20', alt: 'Holi Gulaal Thekua' }],
    price: 360,
    tags: ['puja', 'holi', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
   {
    id: 'raksha-bandhan-thekua',
    name: 'Raksha Bandhan Thekua',
    description: 'A sweet treat for the festival of Rakhi.',
    longDescription: 'Celebrate Raksha Bandhan with this sweet assortment of thekuas, perfect for the occasion.',
    images: [{ id: 'thekua-21', alt: 'Raksha Bandhan Thekua' }],
    price: 450,
    tags: ['puja', 'rakhi', 'festive', 'special-offer'],
    packSizes: ['500g'],
    category: 'puja',
  },
  {
    id: 'thekua-monthly-subscription',
    name: 'Thekua Monthly Subscription',
    description: 'Fresh Thekua delivered to your door every month.',
    longDescription: 'Never run out of your favorite snack! Subscribe to our monthly Thekua box and get a fresh batch of classic ghee thekua delivered to your doorstep every month.',
    images: [{ id: 'thekua-22', alt: 'Thekua Monthly Subscription' }],
    price: 900,
    tags: ['subscription', 'bestseller', 'special-offer'],
    packSizes: ['1kg'],
    category: 'gift',
  }
];

export const testimonials: Testimonial[] = [
    {
        id: '1',
        name: 'Priya Sharma',
        location: 'Mumbai, MH',
        avatar: 'https://picsum.photos/seed/p1/40/40',
        text: 'The Classic Ghee Thekua tastes exactly like the ones my grandmother used to make. It brought back so many childhood memories. Absolutely delicious!',
        rating: 5,
    },
    {
        id: '2',
        name: 'Amit Kumar',
        location: 'Bangalore, KA',
        avatar: 'https://picsum.photos/seed/p2/40/40',
        text: 'I ordered the Festive Combo Pack for Diwali, and it was a huge hit with my family. The quality and packaging were top-notch. Highly recommend!',
        rating: 5,
    },
    {
        id: '3',
        name: 'Sunita Devi',
        location: 'Patna, BR',
        avatar: 'https://picsum.photos/seed/p3/40/40',
        text: 'As someone from Bihar, I can vouch for the authenticity of these Thekuas. The Coconut Crunch is a fantastic innovation. Keep up the great work!',
        rating: 4,
    },
];
