import type { Product, Testimonial } from './types';

export const products: Product[] = [
  {
    id: 'thekua-classic-ghee',
    name: 'Classic Ghee Thekua',
    description: 'The authentic taste of Bihar, made with pure ghee and whole wheat.',
    longDescription: 'Our Classic Ghee Thekua is a tribute to the timeless recipe that has been cherished for generations. Made with premium whole wheat flour, sweetened with jaggery, and fried to a perfect golden-brown in pure desi ghee, each bite offers a crunchy texture and a rich, nutty flavor. It\'s the perfect snack for any time of the day.',
    images: [{ id: 'thekua-1', alt: 'Classic Ghee Thekua' }, { id: 'thekua-2', alt: 'A stack of Thekua' }],
    price: 250,
    tags: ['classic', 'ghee', 'bestseller'],
    packSizes: ['250g', '500g', '1kg'],
    category: 'single',
  },
  {
    id: 'thekua-coconut-crunch',
    name: 'Coconut Crunch Thekua',
    description: 'A delightful twist with the tropical flavor of dried coconut.',
    longDescription: 'Experience a tropical escape with our Coconut Crunch Thekua. We\'ve added generous amounts of finely grated dried coconut to our traditional dough, creating a unique texture and a subtly sweet, aromatic flavor profile. It\'s a modern take on a classic that will leave you wanting more.',
    images: [{ id: 'thekua-3', alt: 'Coconut Crunch Thekua' }, { id: 'thekua-4', alt: 'Thekua with coconut flakes' }],
    price: 280,
    tags: ['coconut', 'new-flavor'],
    packSizes: ['250g', '500g'],
    category: 'single',
  },
  {
    id: 'thekua-dry-fruit-delight',
    name: 'Dry Fruit Delight Thekua',
    description: 'Loaded with premium nuts and raisins for a royal treat.',
    longDescription: 'Indulge in the richness of our Dry Fruit Delight Thekua. This luxurious version is packed with a mix of chopped almonds, cashews, and sweet raisins. The crunch of the nuts and the sweetness of the raisins perfectly complement the rustic flavor of the Thekua, making it a truly decadent snack.',
    images: [{ id: 'thekua-5', alt: 'Dry Fruit Delight Thekua' }, { id: 'thekua-6', alt: 'Thekua with dry fruits' }],
    price: 350,
    tags: ['dry-fruit', 'premium'],
    packSizes: ['500g', '1kg'],
    category: 'single',
  },
  {
    id: 'thekua-sugar-free',
    name: 'Sugar-Free Thekua',
    description: 'The same great taste, sweetened naturally with jaggery.',
    longDescription: 'For our health-conscious customers, we offer a Sugar-Free Thekua that doesn\'t compromise on taste. Sweetened entirely with organic jaggery, this version retains the authentic flavor while being a healthier alternative. Enjoy the guilt-free pleasure of this traditional snack.',
    images: [{ id: 'thekua-7', alt: 'Sugar-Free Thekua' }],
    price: 270,
    tags: ['sugar-free', 'healthy'],
    packSizes: ['250g', '500g'],
    category: 'single',
  },
  {
    id: 'combo-festive-pack',
    name: 'Festive Combo Pack',
    description: 'An assortment of our best Thekuas, perfect for gifting.',
    longDescription: 'Our Festive Combo Pack is the perfect way to celebrate any occasion. It includes a curated selection of our Classic Ghee, Coconut Crunch, and Dry Fruit Delight Thekuas. Beautifully packaged, it makes for an ideal gift for loved ones or a wonderful treat for yourself.',
    images: [{ id: 'thekua-8', alt: 'Festive Combo Pack' }],
    price: 800,
    tags: ['combo', 'gifting', 'festive'],
    packSizes: ['750g'],
    category: 'combo',
  },
];

export const testimonials: Testimonial[] = [
    {
        id: '1',
        name: 'Priya Sharma',
        location: 'Mumbai, MH',
        avatar: 'https://picsum.photos/seed/p1/40/40',
        text: 'The Classic Ghee Thekua tastes exactly like the ones my grandmother used to make. It brought back so many childhood memories. Absolutely delicious!',
        rating: 5,
    },
    {
        id: '2',
        name: 'Amit Kumar',
        location: 'Bangalore, KA',
        avatar: 'https://picsum.photos/seed/p2/40/40',
        text: 'I ordered the Festive Combo Pack for Diwali, and it was a huge hit with my family. The quality and packaging were top-notch. Highly recommend!',
        rating: 5,
    },
    {
        id: '3',
        name: 'Sunita Devi',
        location: 'Patna, BR',
        avatar: 'https://picsum.photos/seed/p3/40/40',
        text: 'As someone from Bihar, I can vouch for the authenticity of these Thekuas. The Coconut Crunch is a fantastic innovation. Keep up the great work!',
        rating: 4,
    },
];
